CREATE TABLE USERS (USERID INT IDENTITY(1,1), USERNAME VARCHAR(20) PRIMARY KEY, PASS VARCHAR(15),NAME VARCHAR(30),MAIL VARCHAR(40),NUMBER VARCHAR(20));

insert into USERS values ('admin','adminpass','OWNERNAME','admin@gmail.com','998877662'),
('akash1','password1','AKASH','akash@gmail.com','5576424875');

select * from USERS;

CREATE TABLE ENQUIRY (ENQUSERID INT IDENTITY(1,1), ENQUSERNAME VARCHAR(20) FOREIGN KEY REFERENCES USERS(USERNAME), ENQSUB VARCHAR(30),ENQMESS VARCHAR(50),ENQDATE DATETIME);

SELECT @@SERVERNAME

SELECT * FROM USERS WHERE USERNAME='admin' AND PASS='adminpass';

SELECT * FROM ENQUIRY;

